# Generated by Django 5.0.4 on 2024-05-10 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palavrao', '0002_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='puzzle_id',
        ),
    ]
