# Generated by Django 5.0.4 on 2024-05-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palavrao', '0003_remove_comment_puzzle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tentativa',
            name='puzzle',
        ),
        migrations.RemoveField(
            model_name='tentativa',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='gostos',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Puzzle',
        ),
        migrations.DeleteModel(
            name='Tentativa',
        ),
    ]
